[package]
name = "bevy_ecs_markers"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.9.1"
bevy_ecs_markers_macros = { path = "macros" }
hashbrown = "0.13.1"

[dev-dependencies]
bevy = "0.9.1"
